name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}${{ matrix.yjit }}
    env:
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-11, windows-2022 ]
        ruby: [ 3.1, 3.0, 2.7 ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby
        uses: MSP-Greg/setup-ruby-pkgs@win-ucrt-2
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: libxml2-dev
          # brew: libxml2
          mingw: libxml2
          bundler-cache: true
          setup-ruby-ref: MSP-Greg/ruby-setup-ruby/win-ucrt-1
        timeout-minutes: 10

      - name: compile
        run:  bundle exec rake compile

      - name: test
        timeout-minutes: 10
        run: bundle exec rake test
